import { createReadStream, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { createServer } from "node:http";
import { extname, join, normalize } from "node:path";
import { fileURLToPath } from "node:url";

const root = process.env.RETROUNLOCK_APP_ROOT || fileURLToPath(new URL(".", import.meta.url));
const userDataRoot = process.env.RETROUNLOCK_DATA_DIR || root;
loadEnv(join(userDataRoot, ".env"));
const config = { apiKey: process.env.RETROACHIEVEMENTS_API_KEY || "", username: process.env.RETROACHIEVEMENTS_USERNAME || "", pollMs: Math.max(5000, Number(process.env.POLL_INTERVAL_MS) || 10000), port: Number(process.env.PORT) || 3000 };
const overlaysPath = join(userDataRoot, "data", "overlays.json");
const clients = new Set(); const seen = new Set();
const GAME_LIST_CACHE_MS = 5 * 60_000;
const GAME_PROGRESS_CACHE_MS = 60_000;
let latest = null; let status = config.apiKey && config.username ? "connecting" : "configuration_required"; let gamesCache = { value: [], expiresAt: 0 }; const gridCache = new Map(); let pollTimer;

function loadEnv(path) { if (!existsSync(path)) return; for (const raw of readFileSync(path, "utf8").split(/\r?\n/)) { const line = raw.trim(); if (!line || line.startsWith("#")) continue; const at = line.indexOf("="); if (at < 1) continue; const key = line.slice(0, at).trim(); const value = line.slice(at + 1).trim().replace(/^['"]|['"]$/g, ""); if (!process.env[key]) process.env[key] = value; } }
function saveConfiguration({ username, apiKey }) { const safeUsername = String(username || "").trim(); const safeApiKey = String(apiKey || "").trim(); if (!/^[A-Za-z0-9_-]{1,50}$/.test(safeUsername) || !/^[A-Za-z0-9]+$/.test(safeApiKey)) throw new Error("Nom d’utilisateur ou clé API invalide."); writeFileSync(join(userDataRoot, ".env"), `RETROACHIEVEMENTS_API_KEY=${safeApiKey}\nRETROACHIEVEMENTS_USERNAME=${safeUsername}\nPOLL_INTERVAL_MS=${config.pollMs}\nPORT=${config.port}\n`, "utf8"); config.apiKey = safeApiKey; config.username = safeUsername; gamesCache = { value: [], expiresAt: 0 }; gridCache.clear(); seen.clear(); latest = null; status = "connecting"; startPolling(); }
function getOverlays() { try { return JSON.parse(readFileSync(overlaysPath, "utf8")); } catch { return []; } }
function saveOverlays(overlays) { mkdirSync(join(userDataRoot, "data"), { recursive: true }); writeFileSync(overlaysPath, `${JSON.stringify(overlays, null, 2)}\n`, "utf8"); }
function safeOverlay(overlay) { return { id: overlay.id, name: overlay.name, layout: overlay.layout || "grid", theme: { accent: overlay.theme?.accent || "#ffd34e", background: overlay.theme?.background || "#0d1119", opacity: overlay.theme?.opacity || 96, columns: overlay.theme?.columns || 10 }, gameId: overlay.gameId, gameTitle: overlay.gameTitle, gameIcon: overlay.gameIcon, consoleName: overlay.consoleName }; }
async function readJson(request) { let body = ""; for await (const chunk of request) body += chunk; return JSON.parse(body || "{}"); }
function broadcast(type, payload) { const message = `event: ${type}\ndata: ${JSON.stringify(payload)}\n\n`; for (const response of clients) response.write(message); }
function publicAchievement(item) { return { id: item.AchievementID, gameId: item.GameID, title: item.Title, description: item.Description, points: item.Points, trueRatio: item.TrueRatio, hardcore: Boolean(item.HardcoreMode), gameTitle: item.GameTitle, consoleName: item.ConsoleName, badgeUrl: item.BadgeURL ? `https://retroachievements.org${item.BadgeURL}` : "", gameIcon: item.GameIcon ? `https://retroachievements.org${item.GameIcon}` : "", unlockedAt: item.Date }; }
async function fetchGrid(gameId) {
  const cached = gridCache.get(gameId);
  if (cached?.value && cached.expiresAt > Date.now()) return cached.value;
  if (cached?.request) return cached.request;
  const request = (async () => {
    const query = new URLSearchParams({ y: config.apiKey, u: config.username, g: String(gameId), a: "1" });
    const response = await fetch(`https://retroachievements.org/API/API_GetGameInfoAndUserProgress.php?${query}`);
    if (!response.ok) throw new Error(`RetroAchievements returned ${response.status}`);
    const game = await response.json();
    const achievements = Object.values(game.Achievements || {}).sort((a,b) => a.DisplayOrder - b.DisplayOrder).map((a) => ({ id:a.ID, title:a.Title, description:a.Description, points:a.Points, earned:Boolean(a.DateEarned), hardcore:Boolean(a.DateEarnedHardcore), badgeUrl:a.BadgeName ? `https://retroachievements.org/Badge/${a.BadgeName}.png` : "" }));
    const value = { title:game.Title, icon:game.ImageIcon ? `https://retroachievements.org${game.ImageIcon}` : "", earned:game.NumAwardedToUser || 0, total:game.NumAchievements || achievements.length, achievements };
    gridCache.set(gameId, { value, expiresAt: Date.now() + GAME_PROGRESS_CACHE_MS });
    return value;
  })();
  gridCache.set(gameId, { request, expiresAt: 0 });
  try { return await request; } catch (error) { gridCache.delete(gameId); throw error; }
}
async function fetchGames(force=false) { if (!config.apiKey || !config.username) return []; if (!force && gamesCache.expiresAt > Date.now()) return gamesCache.value; const query = new URLSearchParams({ y: config.apiKey, u: config.username, c: "50" }); const response = await fetch(`https://retroachievements.org/API/API_GetUserRecentlyPlayedGames.php?${query}`, { headers: { Accept: "application/json" } }); if (!response.ok) throw new Error(`RetroAchievements returned ${response.status}`); const items = await response.json(); gamesCache = { value: Array.isArray(items) ? items.map((game) => ({ id: game.GameID, title: game.Title, consoleName: game.ConsoleName, icon: game.ImageIcon ? `https://retroachievements.org${game.ImageIcon}` : "", achieved: game.NumAchieved, total: game.NumPossibleAchievements })) : [], expiresAt: Date.now() + GAME_LIST_CACHE_MS }; return gamesCache.value; }
async function pollRetroAchievements(initial = false) { if (!config.apiKey || !config.username) return; try { const query = new URLSearchParams({ y: config.apiKey, u: config.username, m: "10" }); const response = await fetch(`https://retroachievements.org/API/API_GetUserRecentAchievements.php?${query}`, { headers: { Accept: "application/json" } }); if (!response.ok) throw new Error(`RetroAchievements returned ${response.status}`); const achievements = await response.json(); if (!Array.isArray(achievements)) throw new Error("Réponse RetroAchievements inattendue"); for (const achievement of [...achievements].reverse()) { const id = `${achievement.AchievementID}:${achievement.Date}:${achievement.HardcoreMode}`; if (seen.has(id)) continue; seen.add(id); gridCache.delete(Number(achievement.GameID)); latest = publicAchievement(achievement); if (!initial) broadcast("unlock", latest); } while (seen.size > 500) seen.delete(seen.values().next().value); status = "connected"; broadcast("status", { status, username: config.username, pollMs: config.pollMs }); } catch (error) { status = "error"; broadcast("status", { status, message: error.message }); console.error(`[RetroUnlock] ${error.message}`); } }
function startPolling() { clearInterval(pollTimer); if (!config.apiKey || !config.username) return; pollRetroAchievements(true); pollTimer = setInterval(() => pollRetroAchievements(false), config.pollMs); }

const contentTypes = { ".css": "text/css; charset=utf-8", ".html": "text/html; charset=utf-8", ".js": "text/javascript; charset=utf-8", ".svg": "image/svg+xml", ".png": "image/png" };
const server = createServer(async (request, response) => {
  const url = new URL(request.url, `http://${request.headers.host}`);
  if (url.pathname === "/api/status") { response.writeHead(200, { "Content-Type": "application/json", "Cache-Control": "no-store" }); response.end(JSON.stringify({ status, configured: Boolean(config.apiKey && config.username), username: config.username || null, pollMs: config.pollMs, latest })); return; }
  if (url.pathname === "/api/configuration" && request.method === "POST") { try { saveConfiguration(await readJson(request)); response.writeHead(204).end(); } catch (error) { response.writeHead(400, { "Content-Type": "application/json" }); response.end(JSON.stringify({ error: error.message })); } return; }
  if (url.pathname === "/api/test-alert" && request.method === "POST") { try { const input = await readJson(request); const gameId = Number(input.gameId); if (!Number.isInteger(gameId) || gameId < 1) throw new Error("Choisis un jeu avant de tester l’alerte."); const achievement = { id: `test-${Date.now()}`, gameId, title: "Test d’animation", description: "Cette alerte est un aperçu envoyé à OBS.", points: 5, trueRatio: 0, hardcore: true, gameTitle: String(input.gameTitle || "RetroAchievements").slice(0, 120), badgeUrl: "", unlockedAt: new Date().toISOString() }; broadcast("test-unlock", achievement); response.writeHead(204).end(); } catch (error) { response.writeHead(400, { "Content-Type": "application/json" }); response.end(JSON.stringify({ error: error.message })); } return; }
  if (url.pathname === "/api/events") { response.writeHead(200, { "Content-Type": "text/event-stream", "Cache-Control": "no-cache", Connection: "keep-alive" }); response.write("retry: 3000\n\n"); clients.add(response); response.write(`event: status\ndata: ${JSON.stringify({ status, configured: Boolean(config.apiKey && config.username), username: config.username || null, pollMs: config.pollMs })}\n\n`); request.on("close", () => clients.delete(response)); return; }
  if (url.pathname === "/api/games" && request.method === "GET") { try { response.writeHead(200, { "Content-Type": "application/json" }); response.end(JSON.stringify({ games: await fetchGames(url.searchParams.get("refresh")==="1") })); } catch (error) { response.writeHead(502, { "Content-Type": "application/json" }); response.end(JSON.stringify({ error: error.message })); } return; }
  if (url.pathname === "/api/preview-grid" && request.method === "GET") { const gameId=Number(url.searchParams.get("gameId")); if(!Number.isInteger(gameId)||gameId<1){response.writeHead(400).end("Jeu invalide");return} try { response.writeHead(200,{"Content-Type":"application/json"});response.end(JSON.stringify({grid:await fetchGrid(gameId)})); } catch(error) { response.writeHead(502,{"Content-Type":"application/json"});response.end(JSON.stringify({error:error.message})); } return; }
  if (url.pathname === "/api/overlays" && request.method === "GET") { response.writeHead(200, { "Content-Type": "application/json" }); response.end(JSON.stringify({ overlays: getOverlays().map(safeOverlay) })); return; }
  if (url.pathname === "/api/overlays" && request.method === "POST") { try { const input = await readJson(request); const gameId = Number(input.gameId); if (!Number.isInteger(gameId) || gameId < 1) throw new Error("Jeu invalide"); const color=(value,fallback)=>/^#[0-9a-f]{6}$/i.test(value||"")?value:fallback; const overlay = { id: crypto.randomUUID().slice(0, 8), name: String(input.name || "Mon overlay").trim().slice(0, 48) || "Mon overlay", layout: input.layout === "alert" ? "alert" : "grid", theme:{accent:color(input.theme?.accent,"#ffd34e"),background:color(input.theme?.background,"#0d1119"),opacity:Math.max(55,Math.min(100,Number(input.theme?.opacity)||96)),columns:Math.max(3,Math.min(12,Number(input.theme?.columns)||10))}, gameId, gameTitle: String(input.gameTitle || "").slice(0, 120), gameIcon: String(input.gameIcon || "").slice(0, 300), consoleName: String(input.consoleName || "").slice(0, 80) }; const overlays = getOverlays(); overlays.push(overlay); saveOverlays(overlays); response.writeHead(201, { "Content-Type": "application/json" }); response.end(JSON.stringify({ overlay: safeOverlay(overlay) })); } catch (error) { response.writeHead(400, { "Content-Type": "application/json" }); response.end(JSON.stringify({ error: error.message })); } return; }
  const gridMatch = url.pathname.match(/^\/api\/overlays\/([a-z0-9-]+)\/grid$/i);
  if (gridMatch && request.method === "GET") { const overlay = getOverlays().find((item) => item.id === gridMatch[1]); if (!overlay) { response.writeHead(404).end("Overlay introuvable"); return; } try { response.writeHead(200, { "Content-Type":"application/json", "Cache-Control":"no-store" }); response.end(JSON.stringify({ grid:await fetchGrid(overlay.gameId), overlay:safeOverlay(overlay) })); } catch (error) { response.writeHead(502, { "Content-Type":"application/json" }); response.end(JSON.stringify({ error:error.message })); } return; }
  const match = url.pathname.match(/^\/api\/overlays\/([a-z0-9-]+)$/i);
  if (match && request.method === "GET") { const overlay = getOverlays().find((item) => item.id === match[1]); if (!overlay) { response.writeHead(404).end("Overlay introuvable"); return; } response.writeHead(200, { "Content-Type": "application/json" }); response.end(JSON.stringify({ overlay: safeOverlay(overlay) })); return; }
  if (match && request.method === "DELETE") { const overlays = getOverlays(); const index = overlays.findIndex((item) => item.id === match[1]); if (index < 0) { response.writeHead(404).end("Overlay introuvable"); return; } overlays.splice(index, 1); saveOverlays(overlays); response.writeHead(204).end(); return; }
  const pathname = url.pathname === "/" ? "/index.html" : url.pathname; const file = normalize(join(root, "public", pathname)); if (!file.startsWith(join(root, "public")) || !existsSync(file)) { response.writeHead(404).end("Not found"); return; } response.writeHead(200, { "Content-Type": contentTypes[extname(file)] || "application/octet-stream", "Cache-Control": "no-cache" }); createReadStream(file).pipe(response);
});
server.listen(config.port, "127.0.0.1", () => console.log(`RetroUnlock Live: http://localhost:${config.port}`));
startPolling();
